"""empty message

Revision ID: 875e6c6adee4
Revises: d89761581f04
Create Date: 2025-07-31 07:50:12.232169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '875e6c6adee4'
down_revision = 'd89761581f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    op.drop_table('barbershop_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbershop_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('google_maps_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boosky_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instagram_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('facebook_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hours_monday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hours_tuesday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hours_wednesday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hours_thursday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hours_friday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hours_saturday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hours_sunday', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='barbershop_info_pkey')
    )
    op.create_table('gallery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gallery_pkey')
    )
    # ### end Alembic commands ###
